svendiedrichsen/jollyday

src/main/resources/descriptions/holiday_descriptions.properties
src/main/resources/descriptions/holiday_descriptions_de.properties
src/main/resources/descriptions/holiday_descriptions_en.properties
src/main/resources/descriptions/holiday_descriptions_fr.properties
src/main/resources/descriptions/holiday_descriptions_nl.properties
src/main/resources/descriptions/holiday_descriptions_pt.properties

in Austria and Bavaria its translated to "Martini". MARTINS_TAG is used
in Austria/Burgenland for the 11.11.
BTW: Are you planning a release of 0.5.2 anytime soon?

Provide a description for MARTINS_TAG. Its the same as MARTINS_DAY, but

---

src/site/apt/usage.apt

Hi,
since in my current project all compiler warnings are converted to errors I couldn't create a manager as indicated in the usage section of the website.
It took my a little while to figure out how to do it properly (and there isn't an example anywhere on the web). I would like to add it to the documentation so other people don't have to do it again.
Thanks for your work,
Leonard

Update documentation to not use deprecated method

---

src/main/resources/holidays/Holidays_cz.xml

Since 2016, Good Friday is declared a public holiday in Czech republic.

Added Good Friday into czech holidays to reflect changes to the legislation.

---

src/main/resources/holidays/Holidays_se.xml

Add defacto holidays for Midsummer's Eve, Christmas Eve and New Year's Eve to the list of Swedish holidays. All days are universally treated as holidays.

Swedish Midsummer's Eve, Christmas Eve and New Year's Eve

---

src/main/resources/holidays/Holidays_se.xml
src/test/java/de/jollyday/tests/HolidaySETest.java
src/test/resources/holidays/Holidays_test_se_2016.xml

Midsummer eve is always on a friday (https://sv.wikipedia.org/wiki/Midsommar).

Corrected Swedish calendar configuration and added test.

---

src/main/resources/holidays/Holidays_ca.xml

- Saint-Jean-Baptiste Day is a public holiday observed in Quebec, Canada annually on June 24th.
https://en.wikipedia.org/wiki/Saint-Jean-Baptiste_Day

Added support for "Saint-Jean-Baptiste" Public Holiday for Quebec,Canada.

---

src/main/java/de/jollyday/parser/impl/RelativeToFixedParser.java
src/test/java/de/jollyday/tests/parsers/RelativeToFixedParserTest.java

The latest version of JollyDay has a bug concerning the RelativeToFixed rule.
All holidays with this relation (Repentance Prayer Day for Saxony/Germany and Victoria Day for Canada) are affected.
Example: Repentance Prayer Day in Saxony/Germany
Rule: Wednesday before 2016-11-23
Result: 23st is a Wednesday so current output is 2016-11-23
Should be: 2016-11-16 (proper date)
Same case for Victoria Day on 2015-05-25. Output is 2015-05-25 but it should be 2015-05-18.
If there someday is a holiday which requires this function as currently implemented, we would propose a second rule RelativeToFixedInclusive or similar.

Fix relativetofixed parser

---

src/main/java/de/jollyday/ManagerParameters.java
src/test/java/de/jollyday/parameter/ManagerParametersTest.java

This change adds a way to create `ManagerParameter` from a `Locale`. This is an attempt to fix my issue #38 .
I tried to find the right place to add the method, but because I'm just starting to use Jollyday I'm not quite sure if the `ManagerParameters` is the correct place to do so. Please suggest a better place if I messed this up.

Add method to create ManagerParameter from Locale

---

.gitignore
bnd.bnd
pom.xml
src/main/java/de/jollyday/configuration/impl/DefaultConfigurationProvider.java
src/main/java/de/jollyday/datasource/ConfigurationDataSourceManager.java
src/main/java/de/jollyday/util/ResourceUtil.java

I added the necessary plugins and config to create an OSGi bundle during the build. This should not influence usage outside of OSGi.
You can install in OSGi by downloading and installing apache karaf 4.1.1 and issue these commands:
install -s mvn:org.threeten/threeten-extra/1.2
install -s mvn:de.jollyday/jollyday/0.5.3-SNAPSHOT
The bundles should start without issues.

Add OSGi support

---

src/main/resources/holidays/Holidays_hu.xml

Good Friday is a holiday in Hungary [since 2017](http://hungarytoday.hu/news/official-good-friday-voted-become-hungarys-eleventh-public-holiday-89938).

#57 Add Good Friday to the Hungarian holidays

---

src/main/java/de/jollyday/configuration/ConfigurationProviderManager.java
src/main/java/de/jollyday/configuration/impl/URLConfigurationProvider.java

Use System.getProperty to get a specific property instead of first
retrieving all properties with System.getProperties() only to read one
property out of it.
This is more friendly to security managers: instead of requiring the
permission to read and even write all properties
("java.util.PropertyPermission" "*" "read,write"), the policy only needs
to allow reading a specific property, which is much more secure.
Depending on the JVM implementation, System.getProperty can also be more
efficient.

Use System.getProperty instead of System.getProperties

---

src/main/resources/holidays/Holidays_de.xml
src/test/resources/holidays/Holidays_test_de_2010.xml

On 22nd of Feb 2018 the Landtag in Schleswig-Hostein has decided to add
the reformation day as an offical holiday in Schleswig-Holstein:
http://www.landtag.ltsh.de/plenumonline/archiv/wp19/09/debatten/07_12.html

Added REFORMATION_DAY for Schleswig-Holstein.

---

src/main/java/de/jollyday/HolidayManager.java
src/main/java/de/jollyday/caching/HolidayManagerValueHandler.java
src/main/java/de/jollyday/util/Cache.java
src/test/java/de/jollyday/tests/HolidayDescriptionTest.java
src/test/java/de/jollyday/tests/HolidayTest.java
src/test/java/de/jollyday/tests/XMLValidationTest.java

Avoid locking and use `ConcurrentHashMap.computeIfAbsent(...)` combination in the Cache.

Avoid locking and use ConcurrentHashMap.computeIfAbsent(...) combination

---

src/main/resources/holidays/Holidays_no.xml

Fix for issue #73
Removed 31. Desember from the Norwegian Calendar 
Added Pentecost (e.g. 20. mai) to the Norwegian Calendar

Fix for issue #73

---

src/main/resources/descriptions/holiday_descriptions.properties
src/main/resources/descriptions/holiday_descriptions_de.properties
src/main/resources/descriptions/holiday_descriptions_en.properties
src/main/resources/descriptions/holiday_descriptions_fr.properties
src/main/resources/descriptions/holiday_descriptions_nl.properties
src/main/resources/descriptions/holiday_descriptions_pt.properties
src/main/resources/descriptions/holiday_descriptions_sv.properties

As it was missing in the holiday descriptions I add the "EUROPE_DAY" entry to all files, adding the translations I could. Unfortunately I am unsure what it is (or would be) called in the Netherlands and Sweden.

Add Europe Day

---

src/main/resources/holidays/Holidays_de.xml

source: https://www.thueringer-landtag.de/service/presse/pressemitteilungen/weltkindertag-am-20-september-wird-gesetzlicher-feiertag/
Based on ThürFGtG §2:
http://landesrecht.thueringen.de/jportal/?quelle=jlink&query=FeiertG+TH&psml=bsthueprod.psml&max=true&aiz=true

Added "Weltkindertag" in Thuringa Germany

---

src/main/resources/holidays/Holidays_jp.xml

If Culture Day falls on a Sunday, it should be moved to the following monday.
https://www.officeholidays.com/holidays/japan/culture-day

add moving condition for japanese culture day

---

src/main/resources/holidays/Holidays_de.xml

In Berlin the 8th of May is a holiday in 2020, see:
https://www.berlin.de/special/jobs-und-ausbildung/nachrichten/berlin/5616720-5510939-8-mai-2020-feiertag-in-berlin.html

Add liberation day for 2020 to Berlin

---

pom.xml

Tested build process with JDK 8, 11, 13-16
This project is used in a JavaEE 7 application which should be upgraded to the new JakartaEE 9.1 on JDK 16. During this process I recognized that there are multiple errors while running maven for this project:
- The generated JAXB classes should always use English for class comments. My machine used German and produced some errors because of umlauts.
- `bnd-maven-plugin` had to be updated because of a ConcurrentModificationException
- `xmlutils-core 2.8.2` depents on the newer `jakarta.xml.bind-api` while the JDK 11 build profile still used the older `javax.xml.bind` dependency. This produced some more errors - like not found modules (`jakarta.activation`) or same packages/classes from multiple JARs.
- Adjusted the JDK 9 build profile to included …

Fix build process for JDK 11-16

---

src/main/resources/holidays/Holidays_co.xml

Calendar adjustment implemented for Colombia for following fixed dates: All saints, Cartagena, Ascension day, Corpus Christi and Sacred heart. Those days needed to be moved to the next monday when day doesn't fall on monday in the year consulted.

Calendar adjustment implemented for Colombia for fixed dates

---

src/main/resources/holidays/Holidays_es.xml

I have added some holidays for the city of Madrid and named with subconfiguration mad. Also, I have corrected another for the region of Madrid and removed Easter day for the whole country as it is just Sunday, not holiday. I have to set them fixed as some years they are moved to Mondays but not always. Having the dates updated for our country is now more important as the new electric tariff considers national fixed holidays as off-peak time, thus being cheaper.

Added missing days for Madrid and removed Easter day
